apiVersion: v1
kind: Pod
metadata:
  name: cleanup
  namespace: dating-app
spec:
  restartPolicy: Never
  containers:
  - name: cleanup
    image: busybox:1.36
    command: ["sh", "-c", "rm -rf /data/pgdata && echo DONE && sleep 5"]
    volumeMounts:
    - name: pg
      mountPath: /data
  volumes:
  - name: pg
    persistentVolumeClaim:
      claimName: postgres-pvc
